// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200502152841_AddUser")]
    partial class AddUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BOL.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "testAddress1",
                            Contact = "1234567890",
                            Name = "test1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "testAddress2",
                            Contact = "2345678901",
                            Name = "test2"
                        });
                });

            modelBuilder.Entity("BOL.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "testAddress1",
                            Name = "Admin",
                            Password = "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA+BTOEEwsNEyYuyrdX6F3ggAAAAACAAAAAAAQZgAAAAEAACAAAAAvUVkEph/QVYMyxqa4G/g0vqbenGbScpAv2OwQOlpW/AAAAAAOgAAAAAIAACAAAAB4NN9Tot7baAdmTaQ4OK49a1jLv7/0VXqNkhdEuJblhhAAAAAhaX8x4tX0JKz8wynz22nlQAAAALXmRHXQEBHoeNRNkno/UODqRcSV/fuAPBt+/gQGv24lvzt/A+UQasFMzuJ7Y4I7tRanuMYeNPnRAmfcW6PLpRQ=",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "testAddress2",
                            Name = "Employee",
                            Password = "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA+BTOEEwsNEyYuyrdX6F3ggAAAAACAAAAAAAQZgAAAAEAACAAAACLmArT294T5BOSJpnA+EXB+NclqmGsO4DyVHYu82nHVQAAAAAOgAAAAAIAACAAAADvlRpV5YqTD0sQ9seNH4r+MjHW3SBdY4BOXnZ4EQB+IiAAAAD9JEtN9/NR4Um3PojeImpURNVuYSBLrtbvE6I6T2MbsEAAAAC2uFAQHByw0EHd7PuZOBqxxJAX62t6pllJobzxKFVVFt+NYKO48OuYzKawjL4fx5VeLVJbmiR8G627+wcGXs1h",
                            Username = "employee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
